### ISSUE TITLE
Cannot import numpy for Klayout in Win7

### ISSUE THREAD

**Issue by diamond2nv** [zwh42/KLayout-PyMacros#1]
请问：是否可以在Windows下为Klayout使用numpy ？ 

Thanks ！

############
环境：
Klayout 64 bit 0.24.10
Win 7 64 bit;
Anaconda3 env 虚拟 python3.4.2 64bit
C:\ProgramData\Anaconda3\envs\py34\Lib
C:\ProgramData\Anaconda3\envs\py34\Lib\site-packages

 import numpy 报错：（对应DLL是：numpy1.13.0的/core/multiarray.pyd）
'''
DLL load failed: 找不到指定的模块。
  C:\ProgramData\Anaconda3\envs\py34\Lib\site-packages\numpy\core\__init__.py:14
  C:\ProgramData\Anaconda3\envs\py34\Lib\site-packages\numpy\lib\type_check.py:11
  C:\ProgramData\Anaconda3\envs\py34\Lib\site-packages\numpy\lib\__init__.py:8
  C:\ProgramData\Anaconda3\envs\py34\Lib\site-packages\numpy\add_newdocs.py:13
  C:\ProgramData\Anaconda3\envs\py34\Lib\site-packages\numpy\__init__.py:142
  C:/Users/xxxxx/KLayout/pymacros/new_python_file_1.py:18
'''

**Comment by zwh42** [comment]
是可以的，可能需要你在sys.path里面自行添加路径
