### ISSUE TITLE
Please add a LICENSE file

### ISSUE THREAD

**Issue by mithro** [zwh42/KLayout-PyMacros#3]
Could you please add a LICENSE file to this repository.

See https://help.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository for more information on how to do this.

**Comment by zwh42** [comment]
Hi @mithro ,
Thanks for your notification! I've added a lincense.

Regards,

**Comment by zwh42** [comment]
Hi @mithro ,
Thanks for your notification! I've added a lincense.

Regards,
